FROM maestroperf/maestro-client:edge as maestro-test-client
ADD test-runner-all-out.sh /usr/bin/test-runner-all-out.sh
ADD test-runner-fair-incremental.sh /usr/bin/test-runner-fair-incremental.sh
VOLUME /maestro/tests/results
